// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: DataMock.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//UserName type for Data Mock Service
// UserNAmeDS used to avoid name conflicts with UserName defined in Service1.proto
type UserNameDS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserNameDS) Reset() {
	*x = UserNameDS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DataMock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserNameDS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNameDS) ProtoMessage() {}

func (x *UserNameDS) ProtoReflect() protoreflect.Message {
	mi := &file_DataMock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNameDS.ProtoReflect.Descriptor instead.
func (*UserNameDS) Descriptor() ([]byte, []int) {
	return file_DataMock_proto_rawDescGZIP(), []int{0}
}

func (x *UserNameDS) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//User type for Data Mock Service
// UserDS used to avoid name conflicts with User defined in Service1.proto
type UserDS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Class string `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Roll  int32  `protobuf:"varint,3,opt,name=roll,proto3" json:"roll,omitempty"`
}

func (x *UserDS) Reset() {
	*x = UserDS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DataMock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDS) ProtoMessage() {}

func (x *UserDS) ProtoReflect() protoreflect.Message {
	mi := &file_DataMock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDS.ProtoReflect.Descriptor instead.
func (*UserDS) Descriptor() ([]byte, []int) {
	return file_DataMock_proto_rawDescGZIP(), []int{1}
}

func (x *UserDS) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDS) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *UserDS) GetRoll() int32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

var File_DataMock_proto protoreflect.FileDescriptor

var file_DataMock_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x20, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x44, 0x53, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x46, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x44, 0x53, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x32, 0x38, 0x0a, 0x0b, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0b, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x44, 0x53, 0x1a, 0x07, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x53, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_DataMock_proto_rawDescOnce sync.Once
	file_DataMock_proto_rawDescData = file_DataMock_proto_rawDesc
)

func file_DataMock_proto_rawDescGZIP() []byte {
	file_DataMock_proto_rawDescOnce.Do(func() {
		file_DataMock_proto_rawDescData = protoimpl.X.CompressGZIP(file_DataMock_proto_rawDescData)
	})
	return file_DataMock_proto_rawDescData
}

var file_DataMock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_DataMock_proto_goTypes = []interface{}{
	(*UserNameDS)(nil), // 0: UserNameDS
	(*UserDS)(nil),     // 1: UserDS
}
var file_DataMock_proto_depIdxs = []int32{
	0, // 0: DataService.GetMockUserData:input_type -> UserNameDS
	1, // 1: DataService.GetMockUserData:output_type -> UserDS
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DataMock_proto_init() }
func file_DataMock_proto_init() {
	if File_DataMock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_DataMock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserNameDS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DataMock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DataMock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_DataMock_proto_goTypes,
		DependencyIndexes: file_DataMock_proto_depIdxs,
		MessageInfos:      file_DataMock_proto_msgTypes,
	}.Build()
	File_DataMock_proto = out.File
	file_DataMock_proto_rawDesc = nil
	file_DataMock_proto_goTypes = nil
	file_DataMock_proto_depIdxs = nil
}
